name: ESGI Micro CI Projects

on: [push, pull_request]

jobs:
  build:
    name: Build Micro CI Projects Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    # Add your build steps here (compile/lint/tests)

  deploy:
    name: Build/Publish Docker Images to DockerHub & Deploy to AWS
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    ## Uncomment to publish docker image
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: esgimicroci2021/al1-projects:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    ## Uncomment to deploy
    # - name: Copy docker compose file and start container
    #   run: |
    #     aws ssm send-command \
    #       --document-name "AWS-RunShellScript" \
    #       --targets '[{"Key":"tag:Name","Values":["micro-ci-1-projects"]}]' \
    #       --parameters '{"commands":["#!/bin/bash","cd /home/ssm-user/micro-ci/projects","wget -q https://raw.githubusercontent.com/esgi-microservices-al1-2021/micro-ci-projects/main/.github/aws/docker-compose.yml -O docker-compose.yml","docker-compose rm -f -s -v","docker-compose pull","docker-compose up -d"]}'